[package]
name = "slack_irc_rust"
version = "0.1.0"
authors = ["Erik <erikdesjardins@users.noreply.github.com>"]

[dependencies]
irc = "0.11"
hyper = "0.9"
slack = "0.14"
lazy_static = "0.1"
regex = "0.1"
toml = "0.1"
rustc-serialize = "0.3"
log = "0.3"
