[package]
name = "slack_irc_rust"
version = "0.1.0"
authors = ["Erik <erikdesjardins@users.noreply.github.com>"]

[dependencies]
irc = "0.11"
slack = "0.13"
lazy_static = "0.1.*"
regex = "0.1"
rustc-serialize = "0.3"
